### PR TITLE
Fix NoiseModel import in qick_start.rst

### PR DESCRIPTION
**Pull request by JLenssen**
**Overview**

Fixed minor typos while exploring the docs.

### CODE REVIEW

**Comment by nelimee** [comment]
Thanks for the fix! Nice catch! @inmzhang do you agree with the change to the `ZXCube` definition?

**Comment by inmzhang** [comment]
I'm fine with that. Thanks for the fix!

**Review by inmzhang — APPROVED** [review]

**Comment by JLenssen** [comment]
Welcome, thanks for developing such a nice tool!

**Comment by nelimee** [comment]
As a test @JLenssen, are you able to merge that PR? I think you are not, due to the failing CI (that is our fault, not yours), but just wanted to check before merging myself.

**Comment by JLenssen** [comment]
@nelimee , nope cannot merge, let's see if it will be fixed with the CI/CD changes in the next PR.

**Comment by nelimee** [comment]
Merging this, CI permissions issues are addressed in #415

**Pull request merged**
