### PR TITLE
Ensuring `simulation` and `CompiledGraph` appear in API docs

### PR DESCRIPTION
**Pull request by KabirDubey**
Small PR to address issue #418. I was exploring #364 and noticed some functions in the `simulation` module were not in the API documentation either, so I update the init file similarly.

### CODE REVIEW

**Comment by KabirDubey** [comment]
Ready for review--looks like the docs updated correctly:

https://tqec.github.io/tqec/pull/430/_autosummary/tqec.simulation.html#module-tqec.simulation

https://tqec.github.io/tqec/pull/430/_autosummary/tqec.compile.CompiledGraph.html#tqec.compile.CompiledGraph

**Comment by nelimee** [comment]
Thanks for the PR! The two added functions from `tqec.simulation.generation` are semi-private. I do not see why a user would need to use them in isolation. Not having them in the `__init__.py` was mostly to reduce clutter in the public interface. Users that really need these functions in isolation can import them, but I do think that making them part of the public and documented API does not add a lot of value to regular users.

**Comment by KabirDubey** [comment]
> Thanks for the PR! The two added functions from `tqec.simulation.generation` are semi-private. I do not see why a user would need to use them in isolation. Not having them in the `__init__.py` was mostly to reduce clutter in the public interface. Users that really need these functions in isolation can import them, but I do think that making them part of the public and documented API does not add a lot of value to regular users.

This makes sense, thanks for the clarification. This PR just adds `CompiledGraph`, then.

**Review by nelimee — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
