### PR TITLE
Fix detectors time coordinate

### PR DESCRIPTION
**Pull request by nelimee**
This commit changes how the time coordinate is handled by `match_detectors_from_flows_shallow` (and so by `annotate_detectors_automatically`). Instead of trying to (and failing to) provide the right time coordinate, the function now inserts a `SHIFT_COORDS` instruction before any batch of detectors.

### CODE REVIEW

**Review by inmzhang — COMMENTED** [review]
1. Now the time begins at 1 because the first bulk of detectors is shifted as well. Would it be better to append the `SHIFT_COORDS` instead of prepend to the detectors?
2. For the timeslices where data qubits are measured, there will be some detectors with the same coordinates. We need to shift within the bulk:
```txt
SHIFT_COORDS(0, 0, 1)
DETECTOR(14, 12, 0) rec[-1] rec[-2] rec[-3]
DETECTOR(12, 10, 0) rec[-3] rec[-4] rec[-5] rec[-7] rec[-8]
DETECTOR(10, 12, 0) rec[-6] rec[-7] rec[-9] rec[-10] rec[-11]
DETECTOR(8, 10, 0) rec[-11] rec[-12] rec[-13]
DETECTOR(6, 4, 0) rec[-14] rec[-15] rec[-16]
DETECTOR(4, 2, 0) rec[-16] rec[-17] rec[-18] rec[-20] rec[-21]
DETECTOR(2, 4, 0) rec[-19] rec[-20] rec[-22] rec[-23] rec[-24]
DETECTOR(0, 2, 0) rec[-24] rec[-25] rec[-26]
DETECTOR(2, 2, 0) rec[-34] rec[-50]
DETECTOR(2, 6, 0) rec[-33] rec[-49]
DETECTOR(4, 0, 0) rec[-32] rec[-48]
DETECTOR(4, 4, 0) rec[-31] rec[-47]
DETECTOR(10, 10, 0) rec[-30] rec[-46]
DETECTOR(10, 14, 0) rec[-29] rec[-45]
DETECTOR(12, 8, 0) rec[-28] rec[-44]
DETECTOR(12, 12, 0) rec[-27] rec[-43]
DETECTOR(0, 2, 0) rec[-26] rec[-42]
DETECTOR(2, 4, 0) rec[-22] rec[-41]
DETECTOR(4, 2, 0) rec[-18] rec[-40]
DETECTOR(6, 4, 0) rec[-14] rec[-39]
DETECTOR(8, 10, 0) rec[-13] rec[-38]
DETECTOR(10, 12, 0) rec[-9] rec[-37]
DETECTOR(12, 10, 0) rec[-5] rec[-36]
DETECTOR(14, 12, 0) rec[-1] rec[-35]
```

**Comment by afowler** [comment]
If it can be done elegantly, time starting at zero and final round of
measurements resulting in two distinct rounds of detectors is ideal.

**Comment by nelimee** [comment]
> If it can be done elegantly, time starting at zero and final round of measurements resulting in two distinct rounds of detectors is ideal.

It should now work like that. The second part "final round of measurements resulting in two distinct rounds" is done by shifting temporally by one the detectors that only contain measurements from the very last round, I do not know if that covers all the cases, but it works in the cases we consider at the moment.

**Comment by afowler** [comment]
That sounds like a reasonable condition that covers all cases I can think
of.

**Comment by inmzhang** [comment]
The data qubits readout can appear in the middle of the circuit. For example, the middle ancilla logical qubit of a logical cnot gates can be measured out earlier in the circuit. The detector coordinates are not shifted for that case:
```txt
# Readout of the middle ancilla logical qubit in a logical cnot
TICK
MX 10 12 14 16 24 26 28 30 40 42 46 48 52 54 58 60
M 0 2 7 8 9 11 15 21 22 23 25 29 35 36 37 38 41 43 44 45 47 53 59 64
OBSERVABLE_INCLUDE(0) rec[-21] rec[-16] rec[-11]
OBSERVABLE_INCLUDE(0) rec[-6]
OBSERVABLE_INCLUDE(1) rec[-21] rec[-16] rec[-11]
OBSERVABLE_INCLUDE(1) rec[-6]
SHIFT_COORDS(0, 0, 1)
DETECTOR(6, 12, 0) rec[-5] rec[-6] rec[-8] rec[-10] rec[-11]
DETECTOR(4, 10, 0) rec[-11] rec[-12] rec[-13] rec[-16] rec[-17]
DETECTOR(2, 12, 0) rec[-15] rec[-16] rec[-18] rec[-20] rec[-21]
DETECTOR(0, 10, 0) rec[-21] rec[-22] rec[-23]
DETECTOR(2, 2, 0) rec[-40] rec[-68]
DETECTOR(2, 6, 0) rec[-39] rec[-67]
DETECTOR(2, 10, 0) rec[-38] rec[-66]
DETECTOR(2, 14, 0) rec[-37] rec[-65]
DETECTOR(4, 0, 0) rec[-36] rec[-64]
DETECTOR(4, 4, 0) rec[-35] rec[-63]
DETECTOR(4, 8, 0) rec[-34] rec[-62]
DETECTOR(4, 12, 0) rec[-33] rec[-61]
DETECTOR(6, 10, 0) rec[-32] rec[-60]
DETECTOR(6, 14, 0) rec[-31] rec[-59]
DETECTOR(8, 8, 0) rec[-30] rec[-58]
DETECTOR(8, 12, 0) rec[-29] rec[-57]
DETECTOR(10, 10, 0) rec[-28] rec[-56]
DETECTOR(10, 14, 0) rec[-27] rec[-55]
DETECTOR(12, 8, 0) rec[-26] rec[-54]
DETECTOR(12, 12, 0) rec[-25] rec[-53]
DETECTOR(0, 2, 0) rec[-24] rec[-52]
DETECTOR(0, 10, 0) rec[-23] rec[-51]
DETECTOR(2, 4, 0) rec[-19] rec[-50]
DETECTOR(2, 12, 0) rec[-18] rec[-49]
DETECTOR(4, 2, 0) rec[-14] rec[-48]
DETECTOR(4, 10, 0) rec[-13] rec[-47]
DETECTOR(6, 4, 0) rec[-9] rec[-46]
DETECTOR(6, 12, 0) rec[-8] rec[-45]
DETECTOR(8, 10, 0) rec[-4] rec[-44]
DETECTOR(10, 12, 0) rec[-3] rec[-43]
DETECTOR(12, 10, 0) rec[-2] rec[-42]
DETECTOR(14, 12, 0) rec[-1] rec[-41]
TICK
```

**Comment by nelimee** [comment]
> The data qubits readout can appear in the middle of the circuit. For example, the middle ancilla logical qubit of a logical cnot gates can be measured out before the last timestep of the circuit. The detector coordinates are not shifted for that case:

This is true. I do not see a good way of implementing that in a good way. The main issue is how to differentiate between detectors at the beginning (due to resets on data qubits) from detectors at the end (due to measurements on data qubits) in a generic enough way. Maybe putting a threshold, for example "all detectors that involve more than `X` measurements from a unique round should be shifted because they are due to measurements on data-qubits"?

**Comment by nelimee** [comment]
> This is true. I do not see a good way of implementing that in a good way. The main issue is how to differentiate between detectors at the beginning (due to resets on data qubits) from detectors at the end (due to measurements on data qubits) in a generic enough way. Maybe putting a threshold, for example "all detectors that involve more than `X` measurements from a unique round should be shifted because they are due to measurements on data-qubits"?

I just did that, shifting the time coordinate of detectors that match the above criteria by 0.5. That leads to some detectors having non-integer time coordinate, which does not seem to be a problem for `stim` but might be a problem for other tools.

**Comment by inmzhang** [comment]
The way I may deal with this issue is:
1. In a moment including detectors, find all the detectors on the same spatial coordinates.
2. Sort them by the minimum value of measurement record they include.
3. Zip together the detectors on different spatial coordinates, increase the time coordinates by the index of the group.

This is the post-processing to correct the detector coordinates for the whole circuit, the idea should be similar:
```py
def correct_detector_time_coordinates(circuit: stim.Circuit) -> stim.Circuit:
    """Post-process a circuit to correct the time coordinates of the detectors."""
    new_circuit = stim.Circuit()
    dt = 0
    detectors_in_moment: dict[tuple[float, float], list[tuple[int, ...]]] = {}

    def drain_moment_detectors() -> None:
        for coordinates, targets_for_detectors in detectors_in_moment.items():
            for i, targets in enumerate(
                sorted(
                    targets_for_detectors,
                    key=lambda ts: min(ts),
                )
            ):
                detector = stim.CircuitInstruction(
                    "DETECTOR",
                    [stim.target_rec(t) for t in targets],
                    coordinates + (float(dt + i),),
                )
                new_circuit.append(detector)
        detectors_in_moment.clear()

    for instruction in circuit:
        assert not isinstance(
            instruction, stim.CircuitRepeatBlock
        ), "Should have no repeat blocks."
        if instruction.name == "DETECTOR":
            coordinates = instruction.gate_args_copy()
            detectors_in_moment.setdefault((coordinates[0], coordinates[1]), []).append(
                tuple(t.value for t in instruction.targets_copy())
            )
            continue
        if instruction.name == "TICK" and detectors_in_moment:
            drain_moment_detectors()
            dt += 1
        new_circuit.append(instruction)
    if detectors_in_moment:
        drain_moment_detectors()
    return new_circuit
```

**Comment by nelimee** [comment]
Isn't the line 
```py
                    coordinates + (float(dt + i),),
```
building detectors that will have a time coordinate that will overlap with the time coordinate of detectors in the next round? I tried to solve that by introducing non-integer time coordinates, but I am not convinced this is the right path.

**Comment by inmzhang** [comment]
I think it’s fine for these detectors to have overlapping time coordinates with the next round? Because it seems a reasonable assumption that no detectors will be present at the same spatial coordinates at the next round, since the flow from the current round is cutoff by the data qubits measurement.

**Comment by nelimee** [comment]
> I think it’s fine for these detectors to have overlapping time coordinates with the next round? Because it seems a reasonable assumption that no detectors will be present at the same spatial coordinates at the next round, since the flow from the current round is cutoff by the data qubits measurement.

The measured logical qubit might be re-initialized just after measurement I think, which would lead to potential overlaps. Also, there are at least 3 different groups at one point in the circuit (detectors with measurement from the previous round, detectors with measurements on data qubit for square plaquettes, detectors with measurements on data qubits for rounded plaquette), so the integer offset version goes further than what I initially thought.

**Comment by inmzhang** [comment]
> The measured logical qubit might be re-initialized just after measurement I think, which would lead to potential overlaps. 

Oh I did not realize this case... Then I'm ok with the non-integer time coordinates because I don't have a better solution in my mind.

**Comment by inmzhang** [comment]
Is it possible to add some unit tests for this PR? It is kind of difficult for me to say it's correct without actually running for a circuit.

**Comment by afowler** [comment]
+1 for this solution, non-integer coordinates seem the best way to handle
mid-circuit data qubit measurement followed by initialization again.

**Comment by nelimee** [comment]
> Is it possible to add some unit tests for this PR? It is kind of difficult for me to say it's correct without actually running for a circuit.

I will need more time to re-understand the existing tests and implement meaningful tests for this PR.

**Comment by inmzhang** [comment]
What's the status on this PR? Can we merge it as it is?

**Comment by nelimee** [comment]
> What's the status on this PR? Can we merge it as it is?

Still not enough tests, still unsure about the validity of the approach. I would be against merging it for the moment.

**Comment by inmzhang** [comment]
> 1. Now the time begins at 1 because the first bulk of detectors is shifted as well. Would it be better to append the `SHIFT_COORDS` instead of prepend to the detectors?
> 
>     2. For the timeslices where data qubits are measured, there will be some detectors with the same coordinates. We need to shift within the bulk:
> 
> 
> ```
> SHIFT_COORDS(0, 0, 1)
> DETECTOR(14, 12, 0) rec[-1] rec[-2] rec[-3]
> DETECTOR(12, 10, 0) rec[-3] rec[-4] rec[-5] rec[-7] rec[-8]
> DETECTOR(10, 12, 0) rec[-6] rec[-7] rec[-9] rec[-10] rec[-11]
> DETECTOR(8, 10, 0) rec[-11] rec[-12] rec[-13]
> DETECTOR(6, 4, 0) rec[-14] rec[-15] rec[-16]
> DETECTOR(4, 2, 0) rec[-16] rec[-17] rec[-18] rec[-20] rec[-21]
> DETECTOR(2, 4, 0) rec[-19] rec[-20] rec[-22] rec[-23] rec[-24]
> DETECTOR(0, 2, 0) rec[-24] rec[-25] rec[-26]
> DETECTOR(2, 2, 0) rec[-34] rec[-50]
> DETECTOR(2, 6, 0) rec[-33] rec[-49]
> DETECTOR(4, 0, 0) rec[-32] rec[-48]
> DETECTOR(4, 4, 0) rec[-31] rec[-47]
> DETECTOR(10, 10, 0) rec[-30] rec[-46]
> DETECTOR(10, 14, 0) rec[-29] rec[-45]
> DETECTOR(12, 8, 0) rec[-28] rec[-44]
> DETECTOR(12, 12, 0) rec[-27] rec[-43]
> DETECTOR(0, 2, 0) rec[-26] rec[-42]
> DETECTOR(2, 4, 0) rec[-22] rec[-41]
> DETECTOR(4, 2, 0) rec[-18] rec[-40]
> DETECTOR(6, 4, 0) rec[-14] rec[-39]
> DETECTOR(8, 10, 0) rec[-13] rec[-38]
> DETECTOR(10, 12, 0) rec[-9] rec[-37]
> DETECTOR(12, 10, 0) rec[-5] rec[-36]
> DETECTOR(14, 12, 0) rec[-1] rec[-35]
> ```

Check before closing: is there any other issue with the coordinates except the two mentioned above?

**Comment by nelimee** [comment]
> Check before closing: is there any other issue with the coordinates except the two mentioned above?

As far as I can remember, everything should be fixed, but tests are missing and the code might benefit from a clean-up/simplification pass. I remember that I was surprised by some test results, but cannot remember which ones.

**Comment by inmzhang** [comment]
> For the timeslices where data qubits are measured, there will be some detectors with the same coordinates. We need to shift within the bulk

I can confirm that this issue still exists. We can close this issue and maybe raise a new issue in `tqecd`.

**Comment by nelimee** [comment]
Closing, will re-open sometime today in `tqecd`.

**Pull request closed without merging**
