### PR TITLE
Allow CI/CD to fail for external PRs without required permissions

### PR DESCRIPTION
**Pull request by JLenssen**
### Overview

There are currently two actions in the CI that require write permission to the repository in order to work correctly: 

- `Add Coverage PR Comment`: Adds code coverage report to PR.
- `Deploy if PR`: Adds documentation generation to PR.

The issue has been reported in #401 .

### Solution

Changing the permissions for external PRs could be a security issue, therefore silent failure was chosen as the preferred method.

This PR adds [ `continue-on-error` ](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error) to allow for step failure, and makes the step `Add comment if PR` dependent on success of `Deploy if PR`.

### CODE REVIEW

**Comment by JLenssen** [comment]
@nelimee I hope the actions will work right away. Changes to actions by externals need to be approved each time, not ideal for debugging.

**Comment by nelimee** [comment]
One minor note: you seem to sign your commits with an email that is not recognized as the same account as the one you are using to submit the PRs. This might impact how you appear as a collaborator to the project (I do not know which account will be picked). This is not an issue for the repository, just checking that this is also not an issue for you.

**Comment by nelimee** [comment]
Seems like the issue comes from the fact that the last step of `deploy` is failing. Maybe just also adding a `continue-on-error` there would be sufficient?

**Comment by JLenssen** [comment]
> One minor note: you seem to sign your commits with an email that is not recognized as the same account as the one you are using to submit the PRs. This might impact how you appear as a collaborator to the project (I do not know which account will be picked). This is not an issue for the repository, just checking that this is also not an issue for you.

Thanks for noticing. Fixed my local git config.

**Review by nelimee — APPROVED** [review]
LGTM, thanks for solving that long-standing and annoying issue :)

You should be able to squash and merge this PR by yourself. If not, that is a permission issue on the repository, so let me know.

**Comment by JLenssen** [comment]
@nelimee apparently I have no write access, so I cannot merge. :/

**Comment by nelimee** [comment]
I just looked at it. It would require us to give write permission to anyone wanting to merge a PR. Let's keep the current status-quo for the moment: users outside of the `tqec` organisation will have to wait for someone in the organisation to merge their PR. Thanks for the contribution!

**Pull request merged**
